name: Touch JS Files and Open PR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  touch-js-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and touch all JS files
        run: |
          for file in $(find . -type f -name '*.js'); do
            touch "$file"
          done

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stage and commit changes
        run: |
          git add '*.js'
          git commit -m "chore: touch all JS files" || echo "No changes to commit"

      - name: Push changes to new branch
        run: |
          BRANCH=auto/touch-js-files-$(date +%s)
          git checkout -b $BRANCH
          git push origin $BRANCH
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | gh auth login --with-token

      - name: Create Pull Request with GitHub CLI
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: |
          gh pr create \
            --title "chore: touch all JS files" \
            --body "This PR touches all JS files in the repository.\n\nCopilot custom instructions are provided in \`copilot-instructions.md\`." \
            --base main \
            --head $BRANCH_NAME

      - name: Add Copilot to PR and provide custom instructions
        run: |
          echo "Please add Copilot to this PR and follow the instructions in copilot-instructions.md."
