name: Touch JS Files and Open PR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  touch-js-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and touch all JS files
        run: |
          for file in $(find . -type f -name '*.js'); do
            touch "$file"
          done

      - name: Modify all JS files to ensure a change
        run: |
          for file in $(find . -type f -name '*.js'); do
            echo "" >> "$file"
          done

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stage and commit changes
        run: |
          git add '*.js'
          git commit -m "chore: touch all JS files" || echo "No changes to commit"

      - name: Push changes to new branch
        run: |
          BRANCH=auto/touch-js-files-$(date +%s)
          git checkout -b $BRANCH
          git push origin $BRANCH
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          unset GITHUB_TOKEN
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Use GitHub Copilot CLI to fix JS file
        run: |
          gh extension install github/gh-copilot
          gh copilot suggest --apply sample.js

      - name: Stage and commit Copilot changes
        run: |
          git add sample.js
          git commit -m "fix: apply Copilot suggestions to sample.js" || echo "No Copilot changes to commit"

      - name: Create Pull Request with GitHub CLI
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: |
          # Only create PR if there are commits ahead of main
          COMMITS_AHEAD=$(git rev-list --count origin/main..$BRANCH_NAME)
          if [ "$COMMITS_AHEAD" -gt 0 ]; then
            gh pr create \
              --title "chore: touch all JS files" \
              --body "This PR touches all JS files in the repository.\n\nCopilot custom instructions are provided in \`copilot-instructions.md\`." \
              --base main \
              --head $BRANCH_NAME
            # Comment Copilot instructions on the PR (mention Copilot for visibility)
            gh pr comment "$BRANCH_NAME" --body "@github-copilot Please follow the custom instructions in copilot-instructions.md:\n\n$(cat copilot-instructions.md)"
          else
            echo "No new commits to create a PR. Skipping PR creation."
          fi
