name: Touch JS Files and Open PR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  touch-js-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and touch all JS files
        run: |
          for file in $(find . -type f -name '*.js'); do
            touch "$file"
          done

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stage and commit changes
        run: |
          git add '*.js'
          git commit -m "chore: touch all JS files" || echo "No changes to commit"

      - name: Push changes to new branch
        run: |
          BRANCH=auto/touch-js-files-$(date +%s)
          git checkout -b $BRANCH
          git push origin $BRANCH
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore: touch all JS files"
          body: |
            This PR touches all JS files in the repository.
            
            Copilot custom instructions are provided in `copilot-instructions.md`.
          branch: ${{ env.BRANCH_NAME }}

      - name: Add Copilot to PR and provide custom instructions
        run: |
          echo "Please add Copilot to this PR and follow the instructions in copilot-instructions.md."
